# Generated by Django 5.0.5 on 2024-06-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='arquivo',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='upload_date',
            new_name='data_de_envio',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_by',
            new_name='enviado_por',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='titulo',
        ),
    ]
