# Generated by Django 5.0.5 on 2024-06-16 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_file_document_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arquivo',
            field=models.FileField(upload_to='documents/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data_de_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload'),
        ),
        migrations.AlterField(
            model_name='document',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='enviado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='document',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
