# Generated by Django 5.0.6 on 2024-06-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_document_arquivo_alter_document_data_de_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data_de_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
    ]
